import { defineRecipe } from '@pandacss/dev';

export const themeSwitcherRecipe = defineRecipe({
  className: 'themeSwitcher',
  jsx: ['ThemeSwitcher'],
  base: {
    position: 'relative',
    borderWidth: '2',
    borderStyle: 'solid',
    borderColor: 'border',
    bg: 'transparent',
    color: 'transparent',
    margin: '8',
    borderRadius: '100',
    cursor: 'pointer',
    display: 'grid',
    lineHeight: 'none',
    width: '14',
    height: '14',
    minWidth: '14',
    minHeight: '14',
    flexShrink: 0,
    aspectRatio: 'square',
    transition: 'all',
    '&:before': {
      content: '""',
      position: 'absolute',
      inset: '0',
      opacity: 0,
      display: 'block',
      borderRadius: '100',
      bg: 'bg.neutral.inverse.bold',
      transition: 'all',
      transitionTimingFunction: 'default',
      transitionDuration: 'normal',
    },
    _hover: {
      cursor: 'pointer',
      bg: 'bg.neutral.inverse.bold',
      borderColor: 'bg.neutral.bold',
      '&:before': {
        inset: '-8',
        bg: 'bg.neutral.inverse.bold',
        opacity: 0.25,
      },
    },
  },
});
